language: java
jdk: oraclejdk8
sudo: required # enabled 30/aug/18 due to travis issue #6593 causing failure
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259
before_install:

  # Fix for broken orcale-java8-installer, as per https://github.com/travis-ci/travis-ci/issues/9512#issuecomment-382235301
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  - sudo apt-get install -y oracle-java8-installer || true
  # TODO remove this kludge and the above || true when the ppa is fixed
  - pushd /var/lib/dpkg/info
  - sudo sed -i 's|JAVA_VERSION=8u161|JAVA_VERSION=8u172|' oracle-java8-installer.*
  - sudo sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/|' oracle-java8-installer.*
  - sudo sed -i 's|SHA256SUM_TGZ="6dbc56a0e3310b69e91bb64db63a485bd7b6a8083f08e48047276380a0e2021e"|SHA256SUM_TGZ="28a00b9400b6913563553e09e8024c286b506d8523334c93ddec6c9ec7e9d346"|' oracle-java8-installer.*
  - sudo sed -i 's|J_DIR=jdk1.8.0_161|J_DIR=jdk1.8.0_172|' oracle-java8-installer.*
  - popd
  - sudo apt-get update
  - sudo apt-get install -y oracle-java8-installer
  # end fix

  # MATSim config
  #- cd $HOME && git clone --depth=1 --branch=kaibranch https://github.com/matsim-org/matsim.git
  #- cd $HOME/matsim && git checkout kaibranch && git log -1
  #- cd $HOME/matsim/examples && mvn clean install -DskipTests -Dmaven.test.skip -Dmaven.javadoc.skip -Dsource.skip -Dassembly.skipAssembly=true
  #- cd $HOME/matsim/matsim && mvn clean install -DskipTests -Dmaven.test.skip -Dmaven.javadoc.skip -Dsource.skip -Dassembly.skipAssembly=true
  # Jill config
  - cd $HOME && git clone --depth=50 --branch=dev https://github.com/agentsoz/jill.git
  - cd $HOME/jill && git checkout dev && git log -1
  #- cd $HOME/jill && git reset --hard 2510bed0037cc44520f2627ef85a4fee369e74a9 # fix commit to use
  - cd $HOME/jill && mvn clean install -N
  - cd $HOME/jill/jill && mvn clean install -DskipTests
  # Diffusion Model config
  - cd $HOME && git clone --depth=50 --branch=master https://github.com/agentsoz/diffusion-model.git
  - cd $HOME/diffusion-model && git log -1
  #- cd $HOME/diffusion-model && git reset --hard 2510bed0037cc44520f2627ef85a4fee369e74a9 # fix commit to use
  - cd $HOME/diffusion-model && mvn clean install -DskipTests

script:
  - cd $TRAVIS_BUILD_DIR && mvn package -B -Dmatsim.preferLocalDtds=true
# --fail-at-end # stop at first error --> easier to debug
# -Dmaven.test.redirectTestOutputToFile # otherwise nearly impossible to debug
env:
  global:
    - MAVEN_OPTS="-Xmx4g -Xms4g"
cache:
  directories:
  - $HOME/.m2
