language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259
before_install:
  - cd $HOME && git clone --depth=1 --branch=kaibranch https://github.com/matsim-org/matsim.git 
  - cd $HOME/matsim && git checkout kaibranch && git log -1
  - cd $HOME/matsim/examples && mvn clean install -DskipTests -Dmaven.test.skip -Dmaven.javadoc.skip -Dsource.skip -Dassembly.skipAssembly=true 
  - cd $HOME/matsim/matsim && mvn clean install -DskipTests -Dmaven.test.skip -Dmaven.javadoc.skip -Dsource.skip -Dassembly.skipAssembly=true 
script:
  - mvn package -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end
env:
  global:
    - MAVEN_OPTS="-Xmx2g"
cache:
  directories:
  - $HOME/.m2

