package io.github.agentsoz.ees.gui.model;

public enum Status{
    NEW, DELEGATE, COMMIT, CFP_READY,
    DECISION_READY, CONFIRM_READY, PROPOSED,
    WAITING_NEIGHBOURS, WAITING_PROPOSALS, WAITING_CONFIRM, WAITING_MANAGER,
    DELEGATED, FAILED, NOT_ASSIGNED, COMMITTED
}